### ISSUE TITLE
"featureCounts -g gene_name" sometimes may not work

### ISSUE THREAD

**Issue by rujpeng** [mikefeixu/RNA-Seq#1]
Hi,

Wonderful pipeline, saved me a lot of time searching through tutorials for data processing and figure presentation!

I noticed that in the script, `STAR_pipeline.sh`, `featureCounts -g gene_name` may require that the GFF must have a "gene_name" field. However for some GFF, there might only be a "gene_id" field instead of "gene_name".

Anyway, thanks for the great pipeline!

Best,
Junhui

**Comment by mikefeixu** [comment]
Hi Junhui,

You are very welcome! Thanks for your feedback. You can always use "featureCounts -g gene_id" when it is available.  It's a parameter that can be determined by users per their reference. 

I am going to add some comments in the code to clear the confusion.

Please feel free to let me know if you have any questions or suggestions.

Best regards,
Fei

**Comment by mikefeixu** [comment]
Fixed documentation.
